### ISSUE TITLE
Watchdog

### ISSUE THREAD

**Issue by JamieH** [JamieH/blog.jamiehankins.co.uk#1]
Need to make a watchdog for the Jekyll node webhook listener

**Comment by Naarkie** [comment]
hows that been going for you

**Comment by HandsomeMatt** [comment]
You are being watched.

**Comment by JamieH** [comment]
I stopped self hosting it and just use GitHub pages :+1:

**Comment by Naarkie** [comment]
cool cool
so how have you been?

**Comment by JamieH** [comment]
uh pretty good
